# see http://docs.travis-ci.com/user/languages/php/ for more hints
language: php

php:
 - 5.4
 - 5.5

before_script:
 - cd nomsky/depend/composer && composer install && cd ../../../

script:
 - nomsky/depend/composer/bin/phpunit --configuration=./src/ci/travis/phpunit.travis.xml

after_script:
 - php nomsky/src/ci/scripts/code-coverage-checker.clover.php nomsky/target/site/phpunit-code-coverage/clover-coverage.xml 80
