# see http://docs.travis-ci.com/user/languages/php/ for more hints
language: php

php:
 - 5.4
 - 5.5

before_script:
 - composer install

script:
 - bash bin/phpunit.sh --configuration ./src/ci/travis/phpunit.xml

after_script:
 - php bin/coverage-checker.clover.php target/site/phpunit-code-coverage/clover-coverage.xml 80
